# Some tweaks to the status line
set -g status-right "%H:%M"

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-features ",xterm*:RGB"

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"

# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g base-index 1
set -g renumber-windows on
